In [1]:
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
import numpy as np

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
cars_train=pd.read_csv(r"E:\Data science\Python\D-TREE\cars_train.csv",header=None)
cars_test=pd.read_csv(r"E:\Data science\Python\D-TREE\cars_test.csv",header=None)

In [4]:
print(cars_train.shape)
cars_train.head()

(1382, 7)


0      1      2     3      4    5      6
0  vhigh   high      3  more  small  low  unacc
1    low  vhigh      3     4  small  med  unacc
2    low   high  5more  more    big  low  unacc
3   high    med      4     2  small  med  unacc
4    low    low      3  more    big  med   good

In [5]:
print(cars_test.shape)
cars_test.head()

(346, 7)


0      1      2     3      4     5      6
0    med  vhigh  5more     4  small   low  unacc
1  vhigh   high      2     2    big   med  unacc
2    low   high      2  more  small   low  unacc
3  vhigh  vhigh      3     2    big  high  unacc
4    low    med      4     4    med   med   good

In [6]:
cars_train.columns=["buying","maint","doors","persons","lug_boot","safety","classes"]
cars_test.columns=["buying","maint","doors","persons","lug_boot","safety","classes"]

In [7]:
cars_train.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
classes     0
dtype: int64

In [8]:
cars_test.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
classes     0
dtype: int64

In [9]:
import numpy as np
import seaborn as sns

In [10]:
cars_test.drop("classes",inplace=True,axis=1)

In [11]:
cars_test.head()

buying  maint  doors persons lug_boot safety
0    med  vhigh  5more       4    small    low
1  vhigh   high      2       2      big    med
2    low   high      2    more    small    low
3  vhigh  vhigh      3       2      big   high
4    low    med      4       4      med    med

In [12]:
cars_test.shape

(346, 6)

In [13]:
colname=cars_train.columns
colname

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'classes'], dtype='object')

In [14]:
# fit get the unique values of the varibale and create the dectionary

In [15]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for x in colname:
    cars_train[x]=le.fit_transform(cars_train[x])

In [16]:
cars_train.head()
#classes
#acc==>0
#good==>1
#unacc==>2
#vgood==>3

buying  maint  doors  persons  lug_boot  safety  classes
0       3      0      1        2         2       1        2
1       1      3      1        1         2       2        2
2       1      0      3        2         0       1        2
3       0      2      2        0         2       2        2
4       1      1      1        2         0       2        1

In [17]:
colname=cars_test.columns
colname

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety'], dtype='object')

In [18]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in cars_test.columns:
    cars_test[i]=le.fit_transform(cars_test[i])

In [19]:
cars_test.head()

buying  maint  doors  persons  lug_boot  safety
0       2      3      3        1         2       1
1       3      0      0        0         0       2
2       1      0      0        2         2       1
3       3      3      1        0         0       0
4       1      2      2        1         1       2

In [20]:
x=cars_train.values[:,0:-1]
y=cars_train.values[:,-1]
y=y.astype(int)

In [21]:
print(x.shape)

(1382, 6)


In [22]:
y.shape

(1382,)

In [23]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x)
x=scaler.transform(x)


In [24]:
print(x)

[[ 1.33507272 -1.3488262  -0.45682233  1.21505861  1.22565305  0.00176987]
 [-0.44760409  1.32688358 -0.45682233 -0.01064285  1.22565305  1.22474807]
 [-0.44760409 -1.3488262   1.33418038  1.21505861 -1.21505663  0.00176987]
 ...
 [-1.33894249  1.32688358  1.33418038 -0.01064285  0.00529821 -1.22120833]
 [ 0.44373431  0.43498032  0.43867903 -0.01064285 -1.21505663  0.00176987]
 [ 0.44373431 -0.45692294  1.33418038  1.21505861  1.22565305 -1.22120833]]


In [25]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=10)

# Running decision tree

In [26]:
from sklearn.tree import DecisionTreeClassifier
model_DecisionTree=DecisionTreeClassifier(criterion="gini",random_state=10)
model_DecisionTree.fit(x_train,y_train)
y_pred=model_DecisionTree.predict(x_test)

In [27]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[ 69   1   1   0]
 [  4   8   0   0]
 [  0   0 185   0]
 [  0   0   0   9]]
0.9783393501805054
              precision    recall  f1-score   support

           0       0.95      0.97      0.96        71
           1       0.89      0.67      0.76        12
           2       0.99      1.00      1.00       185
           3       1.00      1.00      1.00         9

    accuracy                           0.98       277
   macro avg       0.96      0.91      0.93       277
weighted avg       0.98      0.98      0.98       277



In [28]:
model_DecisionTree.score(x_train,y_train)

1.0

In [29]:
#importance of feature
print(list(zip(cars_train.columns[0:-1],model_DecisionTree.feature_importances_)))

[('buying', 0.21976792783843332), ('maint', 0.18220929667385857), ('doors', 0.062005934167191426), ('persons', 0.19425872158174767), ('lug_boot', 0.09772725134941933), ('safety', 0.24403086838934968)]


In [30]:
from sklearn import tree
with open(r"E:\Data science\Python\D-TREE\mode_DecisionTree.txt","w") as graph:
    graph=tree.export_graphviz(model_DecisionTree,feature_names=cars_train.columns[0:-1],out_file=graph)


# svc

In [31]:
#svc=support vector classifier
from sklearn import svm
model_SVC=svm.SVC(kernel="rbf",gamma=0.1,C=90)
model_SVC.fit(x_train,y_train)
y_pred=model_SVC.predict(x_test)

In [32]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[ 69   0   2   0]
 [  2  10   0   0]
 [  0   0 185   0]
 [  0   0   0   9]]
0.9855595667870036
              precision    recall  f1-score   support

           0       0.97      0.97      0.97        71
           1       1.00      0.83      0.91        12
           2       0.99      1.00      0.99       185
           3       1.00      1.00      1.00         9

    accuracy                           0.99       277
   macro avg       0.99      0.95      0.97       277
weighted avg       0.99      0.99      0.99       277



# KNN neighbours

In [33]:
 import numpy as np
from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=5,metric="euclidean")
model_KNN.fit(x_train,y_train)
y_pred=model_KNN.predict(x_test)

In [34]:
int(np.sqrt(len(x_train)))

33

In [35]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[ 66   0   5   0]
 [  8   4   0   0]
 [  1   0 184   0]
 [  2   0   1   6]]
0.9386281588447654
              precision    recall  f1-score   support

           0       0.86      0.93      0.89        71
           1       1.00      0.33      0.50        12
           2       0.97      0.99      0.98       185
           3       1.00      0.67      0.80         9

    accuracy                           0.94       277
   macro avg       0.96      0.73      0.79       277
weighted avg       0.94      0.94      0.93       277



# Logistic Regression

In [36]:
from sklearn.linear_model import LogisticRegression
model_lr=LogisticRegression()
model_lr.fit(x_train,y_train)
y_pred=model_lr.predict(x_test)

In [37]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[ 12   0  59   0]
 [  2   0  10   0]
 [ 18   0 167   0]
 [  7   0   2   0]]
0.6462093862815884
              precision    recall  f1-score   support

           0       0.31      0.17      0.22        71
           1       0.00      0.00      0.00        12
           2       0.70      0.90      0.79       185
           3       0.00      0.00      0.00         9

    accuracy                           0.65       277
   macro avg       0.25      0.27      0.25       277
weighted avg       0.55      0.65      0.58       277



# Tunning and final model creation

In [38]:
cars_test.head()

buying  maint  doors  persons  lug_boot  safety
0       2      3      3        1         2       1
1       3      0      0        0         0       2
2       1      0      0        2         2       1
3       3      3      1        0         0       0
4       1      2      2        1         1       2

In [39]:
test=cars_test.values
test=scaler.transform(test)

In [40]:
#predicting using the decission tree
from sklearn.tree import DecisionTreeClassifier
model_DecisionTree=DecisionTreeClassifier(criterion="gini",random_state=10)
model_DecisionTree.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=10, splitter='best')

In [41]:
test_pred=model_DecisionTree.predict(test)
test_pred

array([2, 2, 2, 2, 1, 2, 0, 0, 2, 0, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 3,
       2, 0, 2, 2, 2, 2, 2, 0, 1, 3, 1, 2, 0, 2, 0, 2, 2, 2, 2, 3, 2, 2,
       0, 0, 2, 2, 3, 2, 2, 2, 1, 2, 0, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0,
       2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 1, 2, 2, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 0, 2, 2, 3, 2, 2, 0, 2, 0, 3, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2,
       2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 3, 2, 2,
       2, 2, 0, 0, 2, 2, 2, 2, 3, 2, 0, 2, 1, 0, 2, 2, 2, 2, 2, 3, 0, 0,
       2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 3, 0, 2, 2, 2, 3, 2, 2, 0, 2,
       2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 3, 2, 2, 0,
       2, 0, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 0, 2,
       2, 2, 0, 2, 2, 0, 2, 2, 2, 1, 1, 2, 2, 2, 0, 2, 2, 0, 3, 3, 0, 2,
       0, 2, 2, 2, 3, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2,

In [42]:
cars_test=pd.read_csv(r"E:\Data science\Python\D-TREE\cars_test.csv",header=None)
cars_test.columns=['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety','classes']
cars_test["Predict"]=test_pred
cars_test["Predict"]=cars_test["Predict"].map({0:"acc",1:"good",2:"unacc",3:"vgood"})
cars_test.head(10)

buying  maint  doors persons lug_boot safety classes Predict
0    med  vhigh  5more       4    small    low   unacc   unacc
1  vhigh   high      2       2      big    med   unacc   unacc
2    low   high      2    more    small    low   unacc   unacc
3  vhigh  vhigh      3       2      big   high   unacc   unacc
4    low    med      4       4      med    med    good    good
5  vhigh    low      3    more      med    low   unacc   unacc
6   high    low  5more    more      med    med     acc     acc
7  vhigh    med      2       4      big   high     acc     acc
8   high  vhigh      4    more      big    low   unacc   unacc
9    low  vhigh      3       4    small   high     acc     acc

In [43]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print(confusion_matrix(cars_test.classes,cars_test.Predict))
print(accuracy_score(cars_test.classes,cars_test.Predict))
print(classification_report(cars_test.classes,cars_test.Predict))

[[ 60   1   3   0]
 [  3  10   0   0]
 [  0   0 251   0]
 [  0   0   0  18]]
0.9797687861271677
              precision    recall  f1-score   support

         acc       0.95      0.94      0.94        64
        good       0.91      0.77      0.83        13
       unacc       0.99      1.00      0.99       251
       vgood       1.00      1.00      1.00        18

    accuracy                           0.98       346
   macro avg       0.96      0.93      0.94       346
weighted avg       0.98      0.98      0.98       346



In [44]:
cars_test.to_excel(r"E:\Data science\Python\D-TREE\output.xlsx",header=True)

In [45]:
#ensemble techniques
#1.Bagging: it is parallel approach 
#2.Boosting
#3.Radom forest (boot straping)

# Random Forest

In [46]:
from sklearn.ensemble import RandomForestClassifier
model_random=RandomForestClassifier(n_estimators=50,random_state=10)
model_random.fit(x_train,y_train)
y_pred=model_random.predict(x_test)

In [47]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred ))

[[ 65   1   5   0]
 [  4   8   0   0]
 [  1   0 184   0]
 [  0   0   0   9]]
0.9602888086642599
              precision    recall  f1-score   support

           0       0.93      0.92      0.92        71
           1       0.89      0.67      0.76        12
           2       0.97      0.99      0.98       185
           3       1.00      1.00      1.00         9

    accuracy                           0.96       277
   macro avg       0.95      0.89      0.92       277
weighted avg       0.96      0.96      0.96       277



In [48]:
from sklearn.ensemble import ExtraTreesClassifier
model_EXTRA=ExtraTreesClassifier(n_estimators=200,random_state=10)
model_EXTRA.fit(x_train,y_train)
y_pred=model_EXTRA .predict(x_test)

In [49]:
 from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred ))

[[ 64   0   7   0]
 [  7   5   0   0]
 [  0   0 185   0]
 [  2   0   0   7]]
0.9422382671480144
              precision    recall  f1-score   support

           0       0.88      0.90      0.89        71
           1       1.00      0.42      0.59        12
           2       0.96      1.00      0.98       185
           3       1.00      0.78      0.88         9

    accuracy                           0.94       277
   macro avg       0.96      0.77      0.83       277
weighted avg       0.94      0.94      0.94       277



# Adaboost classifier 

In [50]:
from sklearn.ensemble import AdaBoostClassifier  
model_ADAA=AdaBoostClassifier(base_estimator=
                              DecisionTreeClassifier(random_state=10),
                              n_estimators=100,random_state=10)
model_ADAA.fit(x_train,y_train)
y_pred=model_ADAA.predict(x_test)

In [51]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred ))

[[ 69   1   1   0]
 [  4   8   0   0]
 [  0   0 185   0]
 [  0   0   0   9]]
0.9783393501805054
              precision    recall  f1-score   support

           0       0.95      0.97      0.96        71
           1       0.89      0.67      0.76        12
           2       0.99      1.00      1.00       185
           3       1.00      1.00      1.00         9

    accuracy                           0.98       277
   macro avg       0.96      0.91      0.93       277
weighted avg       0.98      0.98      0.98       277



# Gradient Boosting classifier

In [52]:
from sklearn.ensemble import GradientBoostingClassifier 
model_GDA=GradientBoostingClassifier(n_estimators=500,random_state=10)
model_GDA.fit(x_train,y_train)
y_pred=model_GDA.predict(x_test)

In [53]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred ))

[[ 71   0   0   0]
 [  2  10   0   0]
 [  0   0 185   0]
 [  0   0   0   9]]
0.9927797833935018
              precision    recall  f1-score   support

           0       0.97      1.00      0.99        71
           1       1.00      0.83      0.91        12
           2       1.00      1.00      1.00       185
           3       1.00      1.00      1.00         9

    accuracy                           0.99       277
   macro avg       0.99      0.96      0.97       277
weighted avg       0.99      0.99      0.99       277



# Running XGBOOST

#####  *HAVE TO INSTALL XGBOST BEFORE RUNNING THIS 2 COMMANDS*

In [54]:
"""from xgboost import XGBClassifier 
model_XGB=XGBClassifier(n_estimators=200,random_state=10)
model_XGB.fit(x_train,y_train)
y_pred=model_XGB.predict(x_test)"""

'from xgboost import XGBClassifier \nmodel_XGB=XGBClassifier(n_estimators=200,random_state=10)\nmodel_XGB.fit(x_train,y_train)\ny_pred=model_XGB.predict(x_test)'

In [55]:
"""from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred ))"""

'from sklearn.metrics import confusion_matrix,accuracy_score,classification_report\nprint(confusion_matrix(y_test,y_pred))\nprint(accuracy_score(y_test,y_pred))\nprint(classification_report(y_test,y_pred ))'

# Enseamble modeling

#### *BEFORE RUNNING THOSE 2 FUNCTION HAVE TO INSTALL XGBOOST*
(pip.istall xgboost)

In [56]:

"""from sklearn.ensemble import VotingClassifier
from sklearn.neighbors import KNeighborsClassifier
#create the sub models
estimators=[]
model2=DecisionTreeClassifier(criterion="gini",random_state=10)
estimators.append(('cart',model2))
model3=SVC(kernel='rbf',C=90,gamma=0.1)
estimators.append(('svm',model3))
model4=KNeighborsClassifier(n_neighbors=5,metric='euclidean')
estimators.append('knn',model4)

#create the ensemble model
ensemble=VotingClassifier(estimators)
ensemble.fit(x_train,y_train)
y_pred=ensemble.predict(x_test)
print(y_pred)"""

'from sklearn.ensemble import VotingClassifier\nfrom sklearn.neighbors import KNeighborsClassifier\n#create the sub models\nestimators=[]\nmodel2=DecisionTreeClassifier(criterion="gini",random_state=10)\nestimators.append((\'cart\',model2))\nmodel3=SVC(kernel=\'rbf\',C=90,gamma=0.1)\nestimators.append((\'svm\',model3))\nmodel4=KNeighborsClassifier(n_neighbors=5,metric=\'euclidean\')\nestimators.append(\'knn\',model4)\n\n#create the ensemble model\nensemble=VotingClassifier(estimators)\nensemble.fit(x_train,y_train)\ny_pred=ensemble.predict(x_test)\nprint(y_pred)'

In [57]:
"""from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred ))"""

'from sklearn.metrics import confusion_matrix,accuracy_score,classification_report\nprint(confusion_matrix(y_test,y_pred))\nprint(accuracy_score(y_test,y_pred))\nprint(classification_report(y_test,y_pred ))'